server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader=true
      routes:
        - id: STUDENT-SERVICE
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/**
        - id: SCHOOL-SERVICE
          uri: lb://SCHOOL-SERVICE
          predicates:
            - Path=/school/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://15.228.220.213:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: 15.228.220.213

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true